home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
]

shop/urls.py
from django.urls import path
from .views import *

app_name = 'store'

urlpatterns = [
    path('store/', shop_view, name='store'),
    path('store/search/<str:q>/', product_search_view, name='search'),
    path('store/categories/<str:slug>/', product_category_page, name='category'),
    path('store/detail/<str:slug>/', product_detail_page, name='detail'),
    path('store/detail/<str:slug>/add-review/',
         product_review_add_view, name='detail-review'),
    # path('store/<str:slug>/add-to-cart/', add_to_cart, name='add-to-cart'),
    # path('store/<str:slug>/remove-from-cart/', remove_from_cart, name='remove-from-cart'),
    # path('store/<str:slug>/reduce-items-in-cart/', reduce_item_number_in_cart, name='reduce-items-in-cart'),
    # path('store/cart/', cart_view, name='cart'),
    # path('store/cart/checkout/', check_out_view, name='checkout'),
    # path('store/confirm-payment/', confirm_payment_view, name='confirm-payment'),
    path('store/confirm-purchase/<id>/',
         comfirm_purchase, name='confirm-purchase'),
    path('store/<str:pk>/delete-all-images/',
         delete_all_item_images, name=''),
    path('store/images/<str:pk>/delete/',
         delete_single_item_image, name=''),
    #     path('store/orders/complete/<str:pk>/',
    #          mark_order_as_completed, name=''),

    path('store/delete-sale/<id>/', delete_sale),

    path('store/item-reviews/<str:slug>/',
         ShopItemReviewApiView.as_view()),
    path('store/sales/create/', SaleCreateApiView.as_view()),
]

sofent/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('', include('research.urls', namespace='research')),
    path('', include('farms.urls', namespace='farms')),
    path('', include('donate.urls', namespace='donate')),
    path('', include('shop.urls', namespace='store')),
    path('accounts/', include('allauth.urls')),
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('templated_email.urls', namespace='templated_email')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "accounts.views.error_404_page"
# handler500 = "accounts.views.error_500_page"

shop/forms.py
from dataclasses import fields
from django import forms
from django.forms.fields import *
from django.forms.widgets import *

from .models import *
from .models import ShopItemReview



PAYMENT_CHOICES = (
  ('c', "Credit card"), 
  ('d', "Pay on delivery")
)

class CheckOutForm(forms.Form):
  first_name = forms.CharField(max_length=255, required=True, widget=forms.TextInput(attrs={
    'class': 'form-control'
  }))
  last_name = forms.CharField(max_length=255, required=True, widget=forms.TextInput(attrs={
    'class': 'form-control'
  }))
  email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={
    'class': 'form-control'
  }))
  phone = forms.CharField(max_length=11,required=True, widget=forms.TextInput(attrs={
    'class': 'form-control'
  }))
  address = forms.CharField(required=True, widget=forms.Textarea(attrs={
    'class': 'form-control'
  }))
  update_profile = forms.BooleanField(label="Use details to update my profile", required=False, widget=forms.CheckboxInput(attrs={
    'class': 'form-check-input'
  }))
  payment_options = forms.ChoiceField(required=True, choices=PAYMENT_CHOICES ,widget=forms.RadioSelect(attrs={
    'class': 'form-check-input',
  }))
  # address = 
  # email = 


class ShopItemReviewForm(forms.ModelForm):

  class Meta:
    model = ShopItemReview
    fields = ['subject', 'stars', 'review']



class SaleCreationForm(forms.ModelForm):

  class Meta:
    model = Sale
    fields = ['price', 'quantity']

shop/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from donate.models import DonateItem
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.contrib import messages
from shop.forms import CheckOutForm, ShopItemReviewForm
from .serializers import SaleSerializer, ShopItemreviewSerializer
from .models import *
from allauth.account.decorators import verified_email_required
from allauth.account.models import EmailAddress
from random import choices, sample
from allauth.account.views import PasswordResetView
from rest_framework.generics import ListAPIView, CreateAPIView
from django.core.mail import send_mass_mail, send_mail
from templated_email import send_templated_mail


# Create your views here.


def shop_view(request):
    template_name = 'store/shop.html'
    paginator = Paginator(Item.objects.all(), 3)
    categories = Category.objects.all()
    cart, created = None, False
    cats = sample(range(1, categories.count() + 1), 2)
    print(cats)
    list1 = Category.objects.get(id=cats[0]).items.all() if Category.objects.get(
        id=cats[0]).items.all().count() < 11 else Category.objects.get(id=cats[0]).items.all()[:10]
    list2 = Category.objects.get(id=cats[1]).items.all() if Category.objects.get(
        id=cats[1]).items.all().count() < 11 else Category.objects.get(id=cats[1]).items.all()[:10]

    if request.user.is_authenticated:
        cart, created = Order.objects.get_or_create(
            user=request.user, ordered=False)

    if request.POST:
        q = request.POST.get('q')
        return redirect(f'/store/search/{q}/')

    page = request.GET.get('page')
    obj_list = paginator.get_page(page)

    return render(request, template_name, {
        'store': True,
        'user': request.user,
        'obj_list': obj_list,
        'categories': categories,
        'cart': cart,
        'list1_name': Category.objects.get(id=cats[0]),
        'list2_name': Category.objects.get(id=cats[1]),
        'list1': list1,
        'list2': list2,
    })


def product_search_view(request, q):
    template_name = 'store/shop.html'
    paginator = Paginator(Item.objects.complex_filter(Q(title__contains=q) | Q(
        category__in=Category.objects.filter(title__icontains=q))), 4)
    categories = Category.objects.all()
    cart, created = None, False
    cats = sample(range(1, categories.count() + 1), 2)
    print(cats)
    list1 = Category.objects.get(id=cats[0]).items.all() if Category.objects.get(
        id=cats[0]).items.all().count() < 11 else Category.objects.get(id=cats[0]).items.all()[:10]
    list2 = Category.objects.get(id=cats[1]).items.all() if Category.objects.get(
        id=cats[1]).items.all().count() < 11 else Category.objects.get(id=cats[1]).items.all()[:10]

    if request.user.is_authenticated:
        cart, created = Order.objects.get_or_create(
            user=request.user, ordered=False)

    if request.POST:
        q = request.POST.get('q')
        return redirect(f'/store/search/{q}/')

    page = request.GET.get('page')
    obj_list = paginator.get_page(page)

    return render(request, template_name, {
        'store': True,
        'user': request.user,
        'obj_list': obj_list,
        'categories': categories,
        'cart': cart,
        'list1_name': Category.objects.get(id=cats[0]),
        'list2_name': Category.objects.get(id=cats[1]),
        'list1': list1,
        'list2': list2,
    })


def product_category_page(request, slug):
    template_name = 'store/shop.html'
    category = Category.objects.get(slug=slug)
    categories = Category.objects.all()
    cats = sample(range(1, categories.count() + 1), 2)
    cart, created = None, False
    list1 = Category.objects.get(id=cats[0]).items.all() if Category.objects.get(
        id=cats[0]).items.all().count() < 11 else Category.objects.get(id=cats[0]).items.all()[:10]
    list2 = Category.objects.get(id=cats[1]).items.all() if Category.objects.get(
        id=cats[1]).items.all().count() < 11 else Category.objects.get(id=cats[1]).items.all()[:10]
    item_qs = Item.objects.complex_filter(Q(category=category))
    paginator = Paginator(item_qs, 3)

    # x = Item.objects.
    if request.user.is_authenticated:
        cart, created = Order.objects.get_or_create(
            user=request.user, ordered=False)

    if request.POST:
        q = request.POST.get('q')
        return redirect(f'/store/search/{q}/')

    page = request.GET.get('page')
    obj_list = paginator.get_page(page)

    return render(request, template_name, {
        'store': True,
        'user': request.user,
        'obj_list': obj_list,
        'categories': categories,
        'cart': cart,
        'list1_name': Category.objects.get(id=cats[0]),
        'list2_name': Category.objects.get(id=cats[1]),
        'list1': list1,
        'list2': list2,
    })


# @verified_email_required
# def cart_view(request):
#     cart, created = Order.objects.get_or_create(
#         user=request.user, ordered=False)
#     categories = Category.objects.all()

#     return render(request, 'store/cart.html', {
#         'store': True,
#         'cart': cart,
#         'categories': categories
#     })


def product_detail_page(request, slug):
    item = Item.objects.get(slug=slug)
    category = item.category
    categories = Category.objects.all()
    user = request.user
    chat, chat_created = None, None
    sales = None
    others = category.items.all().exclude(slug=slug)
    if others.count() > 10:
        others = category.items.all().exclude(slug=slug)[:10]

    if request.user.is_authenticated:
        sales = Sale.objects.complex_filter(Q(buyer=user) & Q(
            payment_confirmed=False) & Q(used=False) & Q(item=item))
        chat, chat_created = SalesChat.objects.get_or_create(
            item=item, buyer=user) if user.is_authenticated else (None, None)

    if request.method == 'POST':
        if user.is_authenticated:
            m = request.POST.get('message')
            message = SalesChatMessage.objects.create(
                message=m, sender=user, reciever=item.seller, thread=chat)
            chat.save()

            protocol = 'https://'
            if not request.is_secure():
                protocol = 'http://'

            send_templated_mail(
                template_name='chat_notification',
                from_email='contact@sofentng.org',
                recipient_list=[item.seller.email],
                context={
                    'receiver': message.reciever,
                    'sender': request.user,
                    'message': message.message,
                    'response_url': protocol + request.get_host() + f'/accounts/e-commerce/store/{item.slug}/chat/{message.reciever.username}/'
                }
            )

        return redirect(f'/store/detail/{slug}/')

    return render(request, 'store/detail.html', {
        'sales': sales,
        'chat': chat,
        'store': True,
        'list': others,
        'item': item,
        'categories': categories,
    })


@verified_email_required
def comfirm_purchase(request, id):
    sale = Sale.objects.get(id=id)
    seller = sale.item.seller
    buyer = sale.buyer
    sale.used = True
    sale.save()

    if request.GET.get('next'):
        next = request.GET.get('next')

    from paystackapi.transaction import Transaction
    from paystackapi.paystack import Paystack
    paystack = Paystack(
        secret_key='sk_test_a689bed51f515c614cd476bd37dd3e0e4efd85e3')
    response = paystack.transaction.verify(sale.id)
    # transaction = Transaction(authorization_key="sk_test_a689bed51f515c614cd476bd37dd3e0e4efd85e3")
    # response  = transaction.verify(order.id)
    if response["message"] == 'Verification successful' and response['data']['status'] == 'success':
        sale.payment_confirmed = True
        sale.save()

        protocol = 'https://'
        if not request.is_secure():
            protocol = 'http://'

        # To Seller
        send_templated_mail(
            template_name='purchase_notification',
            from_email='contact@sofentng.org',
            recipient_list=[seller.email],
            context={
                'intended_receiver': 'seller',
                'response_url': protocol + request.get_host() + f'/accounts/e-commerce/store/{sale.item.slug}/',
                'receiver': seller,
                'sale': sale,
                'sender': buyer,
            }
        )

        # To buyer
        send_templated_mail(
            template_name='buyer_purchase_notification',
            from_email='contact@sofentng.org',
            recipient_list=[buyer.email],
            context={
                'intended_receiver': 'buyer',
                'response_url': protocol + request.get_host() + f'/accounts/e-commerce/orders/',
                'receiver': buyer,
                'sale': sale,
            }
        )

        # To admins
        send_templated_mail(
            template_name='admin_purchase_notification',
            from_email='contact@sofentng.org',
            recipient_list=['contact@sofentng.org', 'admin@sofentng.org'],
            context={
                'intended_receiver': 'buyer',
                'response_url': protocol + request.get_host() + f'/accounts/admin/items/{sale.item.slug}/',
                'sale': sale,
            }
        )
        if next:
            return redirect(next)

        return HttpResponse('Something went wrong')
    else:
        return HttpResponse('Something went wrong')


@verified_email_required
def product_review_add_view(request, slug):
    item = Item.objects.get(slug=slug)

    if request.method == 'POST':
        form = ShopItemReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.item = item
            review.sender = request.user

shop/templates/store/cart.html
{% extends 'base.html' %} {% block 'extra_css' %}
<style>
	.card p {
		font-size: 14px;
	}

	.card .card-img {
		min-width: 100px;
	}

	.form-control {
		outline: none;
	}

	.form-control:focus {
		border-color: #92278f;
		outline: 0;
	}

	.input-group .btn-ceal {
		background-color: var(--color-secondary);
		color: white;
		border: 1px solid var(--color-secondary);
	}
</style>

{% endblock %} {% block 'main' %}
<main id="main pt-1">
	<div class="pt-5 mt-5 shadow-sm" id="breadcrumb" style="background-color: #f6f4f4">
		<div class="container">
			<div class="d-flex justify-content-between align-items-center">
				<h3>Cart</h3>

				<nav aria-label="breadcrumb">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="/">Home</a></li>
						<li class="breadcrumb-item"><a href="/store/">Store</a></li>
						<li class="breadcrumb-item active" aria-current="page">Cart</li>
					</ol>
				</nav>
			</div>
		</div>
	</div>

	<div class="container my-5">
		<div class="row flex-lg-row-reverse gx-3">
			<div class="col-lg-5">
				<div class="card border-0 shadow rounded-1 p-3 mb-4 mt-lg-4 pt-3">
					<div class="d-flex justify-content-between align-items-center">
						<p class="">Subtotal</p>
						<strong>&#8358;{{cart.total_price}}</strong>
					</div>
					<div class="d-flex justify-content-between align-items-center">
						<p class="card-titl">Delivery</p>
						<strong>&#8358;0</strong>
					</div>
					<div class="d-flex justify-content-between align-items-center">
						<p class="card-titl">Total</p>
						<strong>&#8358;{{ cart.total_price }}</strong>
					</div>
					<!-- <div class="input-group">
						<input type="text" class="form-control rounded-0" />
						<button class="btn btn-ceal ms-2 rounded-0">Apply Coupon</button>
					</div> -->
					<a href="/store/cart/checkout/" class="btn btn-ceal rounded-0 mt-2">Proceed to checkout</a>
				</div>
			</div>

			<div class="col-lg-7">
				<p class="text-black-50 mb-1">
					Cart({{ cart.items.count }})
				</p>
				{% for order_item in cart.items.all %}
				<div class="card shadow-sm mb-3">
					<div class="card-body p-0">
						<div class="d-flex">
							<div class="me-1 w-25 card-img">
								<img src="{{order_item.item.get_first_image_url}}" alt="" class="img-fluid w-100 h-100" />
							</div>
							<div>
								<p class="mb-0">{{order_item.item.title}}</p>
								<p class="mb-0">Seller: Store</p>
								<h6>&#8358;{{order_item.item.price}}</h6>
							</div>
						</div>
					</div>
					<div class="card-footer">
						<div class="d-flex justify-content-between align-items-center w-100">
							<div class="">
								<a href="{{order_item.item.remove_from_cart_url}}?next=cart" class="bi bi-trash">
									Remove</a>
							</div>
							<form action="">
								<div class="input-group input-group-sm">
									<a href="{{order_item.item.reduce_items_in_cart_url}}?next=cart"
										class="btn btn-sm btn-ceal fw-bold input-group-text"><i class="bi bi-dash-lg"></i></a>
									<input type="text" class="form-control text-center" style="max-width: 40px"
										value="{{ order_item.quantity }}" />
									<a href="{{order_item.item.add_to_cart_url}}?next=cart"
										class="btn btn-ceal fw-bold input-group-text"><i class="bi bi-plus-lg"></i></a>
								</div>
							</form>
						</div>
					</div>
				</div>
				{% empty %}
				<h4>There are no items in you cart</h4>
				{% endfor %}

			</div>
		</div>
	</div>
</main>
{% endblock %} {% block 'extra_js' %}
<script>
	document.getElementById('header').style.background = 'rgba(0, 0, 0, 0.9)';
	document.getElementById('store-hero').style.display = 'none';
</script>
{% endblock %}

shop/templates/store/confirm-payment.html
{% extends 'base.html' %}


{% block 'extra_css' %}
<link rel="stylesheet" href="/static/assets/css/form-validation.css">
<style>
  :root {
    --bs-primary: #92278f !important;
  }

  .form-check-input:checked {
    background-color: #92278f;
    border-color: #92278f;
  }

  .bg-ceal {
    background-color: var(--color-ceal);
  }

  .text-ceal {
    color: var(--color-ceal);
  }

  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }

  .form-control {
    border-radius: 0 !important;
  }

  .form-control:focus {
    border: 1px solid var(--color-ceal);
  }
</style>
{% endblock %}


{% block 'main' %}
<div class="container pt-5 pb-3 mb-3">
  <main>
    <div class="py-5 text-center">
      <!-- <img class="d-block mx-auto mb-4" src="../assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
      <h2>Checkout form</h2>
      <p class="lead">Below is an example form built entirely with Bootstrap’s form controls. Each required form group
        has a validation state that can be triggered by attempting to submit the form without completing it.</p> -->
    </div>

    <div class="row g-5">
      <div class="col-md-5 col-lg-4 order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-ceal">Your cart</span>
          <span class="badge bg-ceal rounded-pill">{{cart.items.count}}</span>
        </h4>
        <ul class="list-group mb-3 rounded-0">
          {% for order_item in cart.items.all %}
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">{{ order_item.item.title }}</h6>
              <small class="text-muted">Qunatity: {{ order_item.quantity }}</small>
            </div>
            <span class="text-muted">&#8358;{{ order_item.total_price }}</span>
          </li>
          {% endfor %}

          <!-- <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
              <h6 class="my-0">Promo code</h6>
              <small>EXAMPLECODE</small>
            </div>
            <span class="text-success">−$5</span>
          </li> -->
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (NGN)</span>
            <strong>&#8358;{{ cart.total_price }}</strong>
          </li>
        </ul>

        <!-- <form class="card p-2">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Promo code">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </form> -->
      </div>
      <div class="col-md-7 col-lg-8">
        <div class="card">
          <div class="card-header">
            <h4 class="card-title mb-0">Order summary</h4>
          </div>
          <div class="card-body">
            <ul class="list-unstyled">
              <li class="fw-bold">Order #{{cart.id}}</li>
              <li class="my-2"><span class="fw-bold">No of items:</span> {{cart.total_items}}</li>
              <li>
                <span class="fw-bold">Payment method: </span>

                {% if cart.billingaddress.payment_method == 'd' %}
                Pay on delivery
                {% else  %}
                Pay with card
                {% endif %}
              </li>
              <li class="my-2"><span class="fw-bold">Total Payment: </span>&#8358;{{cart.total_price}}</li>
            </ul>
          </div>
          <div class="card-footer bg-white">
            <form action="" method="post" id="form">
              {% csrf_token %}
              <div class="row">
                <div class="col-sm-8">
                  {% if cart.billingaddress.payment_method == 'd' %}
                  <button type="submit" name="confirm" value="confirm" class="btn btn-ceal rounded-1 w-100">Confirm
                    Payment
                  </button>
                  {% else  %}
                  <button type="button" onclick="payWithPaystack()" class="btn btn-ceal rounded-1 w-100">Confirm
                    Payment
                  </button>
                  <button id="submit" type="submit" name="confirm" value="confirm"
                    class="btn btn-ceal rounded-1 w-100 d-none">Confirm
                    Payment
                  </button>
                  {% endif %}
                </div>
                <div class="col-sm-4">
                  <button type="submit" name="cancel" value="cancel" class="btn btn-danger w-100">Cancel</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>
{% endblock %}



{% block 'extra_js' %}
<script src="/static/assets/js/form-validation.js"></script>
<script src="https://js.paystack.co/v1/inline.js"></script>
<script>
  let refID = '{{cart.id}}'

  function payWithPaystack() {
    var handler = PaystackPop.setup({
      key: 'pk_test_ea591b2b61ee08638efa6bc5d666413f704f9cb2', // Replace with your public key
      email: '{{cart.billingaddress.email}}',
      amount: parseInt("{{cart.total_price}}") * 100, // the amount value is multiplied by 100 to convert to the lowest currency unit
      currency: 'NGN', // Use GHS for Ghana Cedis or USD for US Dollars
      ref: refID, // Replace with a reference you generated
      callback: function (response) {
        //this happens after the payment is completed successfully
        var reference = response.reference;
        console.log(reference)
        //alert('Payment complete! Reference: ' + reference);
        $('#submit').click();
        // Make an AJAX call to your server with the reference to verify the transaction
      },
      onClose: function () {
        alert('Transaction was not completed, window closed.');
      },
    });
    handler.openIframe();
  }

</script>
{% endblock %}


</body>

shop/templates/store/index.html
{% extends 'base.html' %}


{% block 'extra_css' %}
<link rel="stylesheet" href="/static/assets/css/form-validation.css">
<style>
  :root {
    --bs-primary: #92278f !important;
  }

  .form-check-input:checked {
    background-color: #92278f;
    border-color: #92278f;
  }

  .bg-ceal {
    background-color: var(--color-ceal);
  }

  .text-ceal {
    color: var(--color-ceal);
  }

  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }

  .form-control {
    border-radius: 0 !important;
  }

  .form-control:focus {
    border: 1px solid var(--color-ceal);
  }
</style>
{% endblock %}


{% block 'main' %}
<div class="container pt-5 pb-3 mb-3">
  <main>
    <div class="py-5 text-center">
      <!-- <img class="d-block mx-auto mb-4" src="../assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
      <h2>Checkout form</h2>
      <p class="lead">Below is an example form built entirely with Bootstrap’s form controls. Each required form group
        has a validation state that can be triggered by attempting to submit the form without completing it.</p> -->
    </div>

    <div class="row g-5">
      <div class="col-md-5 col-lg-4 order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-ceal">Your cart</span>
          <span class="badge bg-ceal rounded-pill">{{cart.items.count}}</span>
        </h4>
        <ul class="list-group mb-3 rounded-0">
          {% for order_item in cart.items.all %}
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">{{ order_item.item.title }}</h6>
              <small class="text-muted">Qunatity: {{ order_item.quantity }}</small>
            </div>
            <span class="text-muted">&#8358;{{ order_item.total_price }}</span>
          </li>
          {% endfor %}

          <!-- <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
              <h6 class="my-0">Promo code</h6>
              <small>EXAMPLECODE</small>
            </div>
            <span class="text-success">−$5</span>
          </li> -->
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (NGN)</span>
            <strong>&#8358;{{ cart.total_price }}</strong>
          </li>
        </ul>

        <!-- <form class="card p-2">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Promo code">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </form> -->
      </div>
      <div class="col-md-7 col-lg-8">
        <h4 class="mb-3">Billing address</h4>
        <form class="needs-validation" novalidate method="post">
          {% csrf_token %}
          <div class="row g-3">
            <div class="col-sm-6">
              <label for="firstName" class="form-label">First name</label>
              <input type="text" name="first_name" class="form-control" id="firstName" placeholder=""
                value="{{request.user.first_name}}" required>
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-sm-6">
              <label for="lastName" class="form-label">Last name</label>
              <input type="text" name="last_name" class="form-control" id="last-name" placeholder=""
                value="{{request.user.last_name}}" required>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>

            <div class="col-12">
              <label for="email" class="form-label">Email</label>
              <input type="email" name="email" class="form-control" id="email" required placeholder="you@example.com"
                value="{{request.user.email}}">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="col-12">
              <label for="phone" class="form-label">Phone</label>
              <input type="tel" maxlength="11" name="phone" class="form-control" id="phone" required
                placeholder="08xxxxxxxxx" value="{{request.user.phone}}">
              <div class="invalid-feedback">
                Please enter a valid phone number for shipping updates.
              </div>
            </div>

            <div class="col-12">
              <label for="address" class="form-label">Address</label>
              <input type="text" name="address" value="{{user.address}}" class="form-control" id="address"
                placeholder="1234 Main St" required>
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>
          </div>

          <hr class="my-4">

          <div class="form-check">
            {{form.update_profile}}
            <label class="form-check-label" for="id_update_profile">Use details to update my profile</label>
          </div>

          <hr class="my-4">

          <h4 class="mb-3">Payment</h4>

          <div class="my-3">
            {% for value, name in form.fields.payment_options.choices %}
            <div class="form-check">
              <input id="{{value}}" name="payment_options" type="radio" value="{{value}}" class="form-check-input"
                required>
              <label class="form-check-label" for="{{value}}">{{ name }}</label>
            </div>
            {% endfor %}
          </div>

          <button class="w-100 btn btn-ceal btn-lg" type="submit">Continue to checkout</button>

          <hr class="my-5">


        </form>
      </div>
    </div>
  </main>
</div>
{% endblock %}



{% block 'extra_js' %}
<script src="/static/assets/js/form-validation.js"></script>
{% endblock %}


</body>